- name: Install redis
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed

- name: Install the latest redis
  ansible.builtin.dnf:
    name: "@postgresql:remi-6.2"
    state: latest

- name: updated address redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
