- name: create roboshop conf in nginx
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed



- name: updated address mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes
